#!/usr/bin/env bash
# .agent/scripts/create-pr.sh
# KAVEN AGENT CORE - Automated PR Creation
# Version: 1.0.0
# Purpose: Create Pull Requests automatically

set -euo pipefail

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m'

echo ""
echo "🚀 Creating Pull Request..."
echo ""

# ==============================================================================
# 1. VALIDATE ENVIRONMENT
# ==============================================================================

# Check if gh CLI is installed
if ! command -v gh &> /dev/null; then
    echo -e "${RED}❌ Error: GitHub CLI (gh) is not installed${NC}"
    echo ""
    echo "Install with:"
    echo "  brew install gh         (macOS)"
    echo "  apt install gh          (Ubuntu/Debian)"
    echo "  https://cli.github.com  (Other)"
    echo ""
    exit 1
fi

# Check if authenticated
if ! gh auth status &> /dev/null; then
    echo -e "${RED}❌ Error: Not authenticated with GitHub${NC}"
    echo ""
    echo "Authenticate with:"
    echo "  gh auth login"
    echo ""
    exit 1
fi

# ==============================================================================
# 2. GET CURRENT BRANCH
# ==============================================================================

CURRENT_BRANCH=$(git rev-parse --abbrev-ref HEAD)

# Validate branch name
if ! echo "$CURRENT_BRANCH" | grep -qE "^(feat|fix|docs|chore|refactor|test)/"; then
    echo -e "${RED}❌ Error: Invalid branch name: $CURRENT_BRANCH${NC}"
    echo ""
    echo "Branch must follow pattern: <type>/<name>"
    echo ""
    echo "Valid types:"
    echo "  feat     - New feature"
    echo "  fix      - Bug fix"
    echo "  docs     - Documentation"
    echo "  chore    - Maintenance"
    echo "  refactor - Refactoring"
    echo "  test     - Tests"
    echo ""
    exit 1
fi

echo "  Branch: $CURRENT_BRANCH"

# ==============================================================================
# 3. PUSH BRANCH
# ==============================================================================

echo ""
echo "📤 Pushing branch..."

if ! git push -u origin "$CURRENT_BRANCH" 2>&1; then
    echo -e "${RED}❌ Error: Failed to push branch${NC}"
    exit 1
fi

echo -e "${GREEN}✅ Branch pushed${NC}"

# ==============================================================================
# 4. GENERATE PR TITLE
# ==============================================================================

# Extract type and name from branch
TYPE=$(echo "$CURRENT_BRANCH" | cut -d'/' -f1)
NAME=$(echo "$CURRENT_BRANCH" | cut -d'/' -f2- | tr '-' ' ' | awk '{for(i=1;i<=NF;i++) $i=toupper(substr($i,1,1)) tolower(substr($i,2))}1')

PR_TITLE="$TYPE: $NAME"

echo ""
echo "  Title: $PR_TITLE"

# ==============================================================================
# 5. GENERATE PR BODY
# ==============================================================================

# Get commit messages
COMMITS=$(git log origin/main..HEAD --format="- %s" 2>/dev/null || git log HEAD~5..HEAD --format="- %s")

# Get diff stats
DIFF_STATS=$(git diff --stat origin/main..HEAD 2>/dev/null || git diff --stat HEAD~1..HEAD)

# Find latest evidence bundle
LATEST_EVIDENCE=""
if [[ -d ".agent/artifacts/evidence" ]]; then
    LATEST_EVIDENCE=$(ls -t .agent/artifacts/evidence/*.json 2>/dev/null | head -1 || echo "")
fi

# Build PR body
PR_BODY=$(cat <<EOF
## 📝 Description

<!-- Describe your changes in detail -->

## 🎯 Type of Change

- [$([[ "$TYPE" == "feat" ]] && echo "x" || echo " ")] feat: New feature
- [$([[ "$TYPE" == "fix" ]] && echo "x" || echo " ")] fix: Bug fix
- [$([[ "$TYPE" == "docs" ]] && echo "x" || echo " ")] docs: Documentation update
- [$([[ "$TYPE" == "chore" ]] && echo "x" || echo " ")] chore: Maintenance
- [$([[ "$TYPE" == "refactor" ]] && echo "x" || echo " ")] refactor: Code refactoring
- [$([[ "$TYPE" == "test" ]] && echo "x" || echo " ")] test: Test addition/update

## 📋 Changes

$COMMITS

## 🧪 Testing

- [ ] Unit tests pass
- [ ] Integration tests pass
- [ ] Manual testing completed

## 📊 Evidence Bundle

### Git Diff Stats

\`\`\`
$DIFF_STATS
\`\`\`

$(if [[ -n "$LATEST_EVIDENCE" ]]; then
    echo "### Latest Evidence Bundle"
    echo ""
    echo "File: \`$(basename "$LATEST_EVIDENCE")\`"
    echo ""
    echo "<details>"
    echo "<summary>View Evidence</summary>"
    echo ""
    echo "\`\`\`json"
    cat "$LATEST_EVIDENCE"
    echo "\`\`\`"
    echo ""
    echo "</details>"
fi)

## ✅ Checklist

- [ ] Code follows style guidelines
- [ ] Types are correct
- [ ] Tests added/updated
- [ ] Documentation updated
- [ ] No breaking changes (or documented)
- [ ] Commits are signed
- [ ] Evidence Bundle attached

---

**Auto-generated by KAVEN AGENT CORE**
EOF
)

# ==============================================================================
# 6. CREATE PR
# ==============================================================================

echo ""
echo "🔀 Creating Pull Request..."

if ! gh pr create \
    --title "$PR_TITLE" \
    --body "$PR_BODY" \
    --base main \
    --head "$CURRENT_BRANCH" 2>&1; then
    
    echo -e "${RED}❌ Error: Failed to create PR${NC}"
    exit 1
fi

# ==============================================================================
# 7. SUCCESS
# ==============================================================================

PR_URL=$(gh pr view --json url -q .url 2>/dev/null || echo "")

echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo -e "${GREEN}✅ PR created successfully!${NC}"
echo ""
if [[ -n "$PR_URL" ]]; then
    echo "  URL: $PR_URL"
fi
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""

exit 0
