import { PrismaClient, CapabilitySensitivity, CapabilityScope } from '@prisma/client';

const prisma = new PrismaClient();

/**
 * Seed de Capabilities - Permissões Atômicas
 * 
 * Organizado por categoria:
 * - Support (12 capabilities)
 * - DevOps (15 capabilities)
 * - Finance (12 capabilities)
 * - Marketing (10 capabilities)
 * - Management (11 capabilities)
 * 
 * Total: 60 capabilities
 */

export async function seedCapabilities() {
  console.log('🔐 Seeding Capabilities...');

  const capabilities = [
    // ===========================
    // SUPPORT (12 capabilities)
    // ===========================
    {
      code: 'tickets.read',
      resource: 'tickets',
      action: 'read',
      description: 'Visualizar tickets de suporte',
      category: 'Support',
      sensitivity: CapabilitySensitivity.NORMAL,
      scope: CapabilityScope.SPACE,
    },
    {
      code: 'tickets.create',
      resource: 'tickets',
      action: 'create',
      description: 'Criar novos tickets',
      category: 'Support',
      sensitivity: CapabilitySensitivity.NORMAL,
      scope: CapabilityScope.SPACE,
    },
    {
      code: 'tickets.update',
      resource: 'tickets',
      action: 'update',
      description: 'Atualizar tickets existentes',
      category: 'Support',
      sensitivity: CapabilitySensitivity.NORMAL,
      scope: CapabilityScope.ASSIGNED,
    },
    {
      code: 'tickets.delete',
      resource: 'tickets',
      action: 'delete',
      description: 'Excluir tickets',
      category: 'Support',
      sensitivity: CapabilitySensitivity.SENSITIVE,
      scope: CapabilityScope.SPACE,
      requiresApproval: true,
    },
    {
      code: 'tickets.assign',
      resource: 'tickets',
      action: 'assign',
      description: 'Atribuir tickets a agentes',
      category: 'Support',
      sensitivity: CapabilitySensitivity.NORMAL,
      scope: CapabilityScope.SPACE,
    },
    {
      code: 'tickets.close',
      resource: 'tickets',
      action: 'close',
      description: 'Fechar tickets resolvidos',
      category: 'Support',
      sensitivity: CapabilitySensitivity.NORMAL,
      scope: CapabilityScope.ASSIGNED,
    },
    {
      code: 'tickets.reopen',
      resource: 'tickets',
      action: 'reopen',
      description: 'Reabrir tickets fechados',
      category: 'Support',
      sensitivity: CapabilitySensitivity.NORMAL,
      scope: CapabilityScope.SPACE,
    },
    {
      code: 'tickets.export',
      resource: 'tickets',
      action: 'export',
      description: 'Exportar dados de tickets',
      category: 'Support',
      sensitivity: CapabilitySensitivity.SENSITIVE,
      scope: CapabilityScope.SPACE,
    },
    {
      code: 'customers.read',
      resource: 'customers',
      action: 'read',
      description: 'Visualizar dados de clientes',
      category: 'Support',
      sensitivity: CapabilitySensitivity.SENSITIVE,
      scope: CapabilityScope.TENANT,
    },
    {
      code: 'customers.update',
      resource: 'customers',
      action: 'update',
      description: 'Atualizar dados de clientes',
      category: 'Support',
      sensitivity: CapabilitySensitivity.SENSITIVE,
      scope: CapabilityScope.TENANT,
    },
    {
      code: 'kb.read',
      resource: 'kb',
      action: 'read',
      description: 'Visualizar base de conhecimento',
      category: 'Support',
      sensitivity: CapabilitySensitivity.NORMAL,
      scope: CapabilityScope.GLOBAL,
    },
    {
      code: 'kb.manage',
      resource: 'kb',
      action: 'manage',
      description: 'Gerenciar artigos da base de conhecimento',
      category: 'Support',
      sensitivity: CapabilitySensitivity.NORMAL,
      scope: CapabilityScope.SPACE,
    },
    {
      code: 'auth.2fa_reset.request',
      resource: 'auth',
      action: '2fa_reset_request',
      description: 'Solicitar reset de 2FA para um usuário',
      category: 'Support',
      sensitivity: CapabilitySensitivity.HIGHLY_SENSITIVE,
      scope: CapabilityScope.TENANT,
    },
    {
      code: 'auth.2fa_reset.execute',
      resource: 'auth',
      action: '2fa_reset_execute',
      description: 'Executar reset de 2FA para um usuário',
      category: 'Support',
      sensitivity: CapabilitySensitivity.CRITICAL,
      scope: CapabilityScope.TENANT,
      requiresMFA: true,
      requiresApproval: true,
    },

    // ===========================
    // DEVOPS (15 capabilities)
    // ===========================
    {
      code: 'servers.read',
      resource: 'servers',
      action: 'read',
      description: 'Visualizar informações de servidores',
      category: 'DevOps',
      sensitivity: CapabilitySensitivity.SENSITIVE,
      scope: CapabilityScope.GLOBAL,
    },
    {
      code: 'servers.manage',
      resource: 'servers',
      action: 'manage',
      description: 'Gerenciar configurações de servidores',
      category: 'DevOps',
      sensitivity: CapabilitySensitivity.CRITICAL,
      scope: CapabilityScope.GLOBAL,
      requiresMFA: true,
      requiresApproval: true,
    },
    {
      code: 'deployments.read',
      resource: 'deployments',
      action: 'read',
      description: 'Visualizar histórico de deployments',
      category: 'DevOps',
      sensitivity: CapabilitySensitivity.NORMAL,
      scope: CapabilityScope.GLOBAL,
    },
    {
      code: 'deployments.create',
      resource: 'deployments',
      action: 'create',
      description: 'Criar novos deployments',
      category: 'DevOps',
      sensitivity: CapabilitySensitivity.CRITICAL,
      scope: CapabilityScope.GLOBAL,
      requiresMFA: true,
    },
    {
      code: 'deployments.rollback',
      resource: 'deployments',
      action: 'rollback',
      description: 'Fazer rollback de deployments',
      category: 'DevOps',
      sensitivity: CapabilitySensitivity.CRITICAL,
      scope: CapabilityScope.GLOBAL,
      requiresMFA: true,
      requiresApproval: true,
    },
    {
      code: 'logs.read',
      resource: 'logs',
      action: 'read',
      description: 'Visualizar logs do sistema',
      category: 'DevOps',
      sensitivity: CapabilitySensitivity.SENSITIVE,
      scope: CapabilityScope.GLOBAL,
    },
    {
      code: 'logs.export',
      resource: 'logs',
      action: 'export',
      description: 'Exportar logs do sistema',
      category: 'DevOps',
      sensitivity: CapabilitySensitivity.HIGHLY_SENSITIVE,
      scope: CapabilityScope.GLOBAL,
      requiresApproval: true,
    },
    {
      code: 'monitoring.read',
      resource: 'monitoring',
      action: 'read',
      description: 'Visualizar métricas de monitoramento',
      category: 'DevOps',
      sensitivity: CapabilitySensitivity.NORMAL,
      scope: CapabilityScope.GLOBAL,
    },
    {
      code: 'monitoring.manage',
      resource: 'monitoring',
      action: 'manage',
      description: 'Gerenciar alertas e dashboards',
      category: 'DevOps',
      sensitivity: CapabilitySensitivity.SENSITIVE,
      scope: CapabilityScope.GLOBAL,
    },
    {
      code: 'database.read',
      resource: 'database',
      action: 'read',
      description: 'Visualizar informações do banco de dados',
      category: 'DevOps',
      sensitivity: CapabilitySensitivity.HIGHLY_SENSITIVE,
      scope: CapabilityScope.GLOBAL,
      requiresMFA: true,
    },
    {
      code: 'database.backup',
      resource: 'database',
      action: 'backup',
      description: 'Criar backups do banco de dados',
      category: 'DevOps',
      sensitivity: CapabilitySensitivity.CRITICAL,
      scope: CapabilityScope.GLOBAL,
      requiresMFA: true,
    },
    {
      code: 'database.restore',
      resource: 'database',
      action: 'restore',
      description: 'Restaurar backups do banco de dados',
      category: 'DevOps',
      sensitivity: CapabilitySensitivity.CRITICAL,
      scope: CapabilityScope.GLOBAL,
      requiresMFA: true,
      requiresApproval: true,
    },
    {
      code: 'secrets.read',
      resource: 'secrets',
      action: 'read',
      description: 'Visualizar secrets e variáveis de ambiente',
      category: 'DevOps',
      sensitivity: CapabilitySensitivity.CRITICAL,
      scope: CapabilityScope.GLOBAL,
      requiresMFA: true,
    },
    {
      code: 'secrets.manage',
      resource: 'secrets',
      action: 'manage',
      description: 'Gerenciar secrets e variáveis de ambiente',
      category: 'DevOps',
      sensitivity: CapabilitySensitivity.CRITICAL,
      scope: CapabilityScope.GLOBAL,
      requiresMFA: true,
      requiresApproval: true,
    },
    {
      code: 'incidents.manage',
      resource: 'incidents',
      action: 'manage',
      description: 'Gerenciar incidentes de produção',
      category: 'DevOps',
      sensitivity: CapabilitySensitivity.SENSITIVE,
      scope: CapabilityScope.GLOBAL,
    },

    // ===========================
    // FINANCE (12 capabilities)
    // ===========================
    {
      code: 'invoices.read',
      resource: 'invoices',
      action: 'read',
      description: 'Visualizar faturas',
      category: 'Finance',
      sensitivity: CapabilitySensitivity.SENSITIVE,
      scope: CapabilityScope.TENANT,
    },
    {
      code: 'invoices.create',
      resource: 'invoices',
      action: 'create',
      description: 'Criar novas faturas',
      category: 'Finance',
      sensitivity: CapabilitySensitivity.SENSITIVE,
      scope: CapabilityScope.TENANT,
    },
    {
      code: 'invoices.update',
      resource: 'invoices',
      action: 'update',
      description: 'Atualizar faturas existentes',
      category: 'Finance',
      sensitivity: CapabilitySensitivity.SENSITIVE,
      scope: CapabilityScope.TENANT,
      requiresApproval: true,
    },
    {
      code: 'invoices.delete',
      resource: 'invoices',
      action: 'delete',
      description: 'Excluir faturas',
      category: 'Finance',
      sensitivity: CapabilitySensitivity.HIGHLY_SENSITIVE,
      scope: CapabilityScope.TENANT,
      requiresMFA: true,
      requiresApproval: true,
    },
    {
      code: 'payments.read',
      resource: 'payments',
      action: 'read',
      description: 'Visualizar pagamentos',
      category: 'Finance',
      sensitivity: CapabilitySensitivity.SENSITIVE,
      scope: CapabilityScope.TENANT,
    },
    {
      code: 'payments.process',
      resource: 'payments',
      action: 'process',
      description: 'Processar pagamentos',
      category: 'Finance',
      sensitivity: CapabilitySensitivity.HIGHLY_SENSITIVE,
      scope: CapabilityScope.TENANT,
      requiresMFA: true,
    },
    {
      code: 'refunds.create',
      resource: 'refunds',
      action: 'create',
      description: 'Criar reembolsos',
      category: 'Finance',
      sensitivity: CapabilitySensitivity.HIGHLY_SENSITIVE,
      scope: CapabilityScope.TENANT,
      requiresApproval: true,
    },
    {
      code: 'refunds.approve',
      resource: 'refunds',
      action: 'approve',
      description: 'Aprovar reembolsos',
      category: 'Finance',
      sensitivity: CapabilitySensitivity.CRITICAL,
      scope: CapabilityScope.TENANT,
      requiresMFA: true,
    },
    {
      code: 'subscriptions.read',
      resource: 'subscriptions',
      action: 'read',
      description: 'Visualizar assinaturas',
      category: 'Finance',
      sensitivity: CapabilitySensitivity.SENSITIVE,
      scope: CapabilityScope.TENANT,
    },
    {
      code: 'subscriptions.manage',
      resource: 'subscriptions',
      action: 'manage',
      description: 'Gerenciar assinaturas',
      category: 'Finance',
      sensitivity: CapabilitySensitivity.SENSITIVE,
      scope: CapabilityScope.TENANT,
    },
    {
      code: 'reports.financial',
      resource: 'reports',
      action: 'financial',
      description: 'Gerar relatórios financeiros',
      category: 'Finance',
      sensitivity: CapabilitySensitivity.HIGHLY_SENSITIVE,
      scope: CapabilityScope.GLOBAL,
    },
    {
      code: 'analytics.revenue',
      resource: 'analytics',
      action: 'revenue',
      description: 'Visualizar analytics de receita',
      category: 'Finance',
      sensitivity: CapabilitySensitivity.HIGHLY_SENSITIVE,
      scope: CapabilityScope.GLOBAL,
    },

    // ===========================
    // MARKETING (10 capabilities)
    // ===========================
    {
      code: 'campaigns.read',
      resource: 'campaigns',
      action: 'read',
      description: 'Visualizar campanhas de marketing',
      category: 'Marketing',
      sensitivity: CapabilitySensitivity.NORMAL,
      scope: CapabilityScope.SPACE,
    },
    {
      code: 'campaigns.create',
      resource: 'campaigns',
      action: 'create',
      description: 'Criar novas campanhas',
      category: 'Marketing',
      sensitivity: CapabilitySensitivity.NORMAL,
      scope: CapabilityScope.SPACE,
    },
    {
      code: 'campaigns.update',
      resource: 'campaigns',
      action: 'update',
      description: 'Atualizar campanhas existentes',
      category: 'Marketing',
      sensitivity: CapabilitySensitivity.NORMAL,
      scope: CapabilityScope.SPACE,
    },
    {
      code: 'campaigns.delete',
      resource: 'campaigns',
      action: 'delete',
      description: 'Excluir campanhas',
      category: 'Marketing',
      sensitivity: CapabilitySensitivity.SENSITIVE,
      scope: CapabilityScope.SPACE,
      requiresApproval: true,
    },
    {
      code: 'emails.send',
      resource: 'emails',
      action: 'send',
      description: 'Enviar emails de marketing',
      category: 'Marketing',
      sensitivity: CapabilitySensitivity.SENSITIVE,
      scope: CapabilityScope.SPACE,
    },
    {
      code: 'emails.templates',
      resource: 'emails',
      action: 'templates',
      description: 'Gerenciar templates de email',
      category: 'Marketing',
      sensitivity: CapabilitySensitivity.NORMAL,
      scope: CapabilityScope.SPACE,
    },
    {
      code: 'analytics.marketing',
      resource: 'analytics',
      action: 'marketing',
      description: 'Visualizar analytics de marketing',
      category: 'Marketing',
      sensitivity: CapabilitySensitivity.NORMAL,
      scope: CapabilityScope.SPACE,
    },
    {
      code: 'leads.read',
      resource: 'leads',
      action: 'read',
      description: 'Visualizar leads',
      category: 'Marketing',
      sensitivity: CapabilitySensitivity.SENSITIVE,
      scope: CapabilityScope.SPACE,
    },
    {
      code: 'leads.manage',
      resource: 'leads',
      action: 'manage',
      description: 'Gerenciar leads',
      category: 'Marketing',
      sensitivity: CapabilitySensitivity.SENSITIVE,
      scope: CapabilityScope.SPACE,
    },
    {
      code: 'content.publish',
      resource: 'content',
      action: 'publish',
      description: 'Publicar conteúdo',
      category: 'Marketing',
      sensitivity: CapabilitySensitivity.NORMAL,
      scope: CapabilityScope.SPACE,
    },

    // ===========================
    // MANAGEMENT (11 capabilities)
    // ===========================
    {
      code: 'users.read',
      resource: 'users',
      action: 'read',
      description: 'Visualizar usuários',
      category: 'Management',
      sensitivity: CapabilitySensitivity.SENSITIVE,
      scope: CapabilityScope.TENANT,
    },
    {
      code: 'users.create',
      resource: 'users',
      action: 'create',
      description: 'Criar novos usuários',
      category: 'Management',
      sensitivity: CapabilitySensitivity.SENSITIVE,
      scope: CapabilityScope.TENANT,
    },
    {
      code: 'users.update',
      resource: 'users',
      action: 'update',
      description: 'Atualizar usuários existentes',
      category: 'Management',
      sensitivity: CapabilitySensitivity.SENSITIVE,
      scope: CapabilityScope.TENANT,
    },
    {
      code: 'users.delete',
      resource: 'users',
      action: 'delete',
      description: 'Excluir usuários',
      category: 'Management',
      sensitivity: CapabilitySensitivity.HIGHLY_SENSITIVE,
      scope: CapabilityScope.TENANT,
      requiresApproval: true,
    },
    {
      code: 'roles.read',
      resource: 'roles',
      action: 'read',
      description: 'Visualizar roles e permissões',
      category: 'Management',
      sensitivity: CapabilitySensitivity.SENSITIVE,
      scope: CapabilityScope.SPACE,
    },
    {
      code: 'roles.manage',
      resource: 'roles',
      action: 'manage',
      description: 'Gerenciar roles e permissões',
      category: 'Management',
      sensitivity: CapabilitySensitivity.CRITICAL,
      scope: CapabilityScope.SPACE,
      requiresMFA: true,
      requiresApproval: true,
    },
    {
      code: 'audit.read',
      resource: 'audit',
      action: 'read',
      description: 'Visualizar logs de auditoria',
      category: 'Management',
      sensitivity: CapabilitySensitivity.HIGHLY_SENSITIVE,
      scope: CapabilityScope.GLOBAL,
    },
    {
      code: 'audit.export',
      resource: 'audit',
      action: 'export',
      description: 'Exportar logs de auditoria',
      category: 'Management',
      sensitivity: CapabilitySensitivity.CRITICAL,
      scope: CapabilityScope.GLOBAL,
      requiresMFA: true,
      requiresApproval: true,
    },
    {
      code: 'settings.read',
      resource: 'settings',
      action: 'read',
      description: 'Visualizar configurações da plataforma',
      category: 'Management',
      sensitivity: CapabilitySensitivity.SENSITIVE,
      scope: CapabilityScope.GLOBAL,
    },
    {
      code: 'settings.manage',
      resource: 'settings',
      action: 'manage',
      description: 'Gerenciar configurações da plataforma',
      category: 'Management',
      sensitivity: CapabilitySensitivity.CRITICAL,
      scope: CapabilityScope.GLOBAL,
      requiresMFA: true,
      requiresApproval: true,
    },
    {
      code: 'impersonate.user',
      resource: 'impersonate',
      action: 'user',
      description: 'Impersonar outros usuários',
      category: 'Management',
      sensitivity: CapabilitySensitivity.CRITICAL,
      scope: CapabilityScope.GLOBAL,
      requiresMFA: true,
      requiresApproval: true,
    },
    {
      code: 'users.export',
      resource: 'users',
      action: 'export',
      description: 'Exportar lista de usuários (CSV)',
      category: 'Management',
      sensitivity: CapabilitySensitivity.HIGHLY_SENSITIVE,
      scope: CapabilityScope.TENANT,
      requiresMFA: true,
      requiresApproval: true,
    },
  ];

  let created = 0;
  let skipped = 0;

  for (const capability of capabilities) {
    const existing = await prisma.capability.findUnique({
      where: { code: capability.code },
    });

    if (existing) {
      skipped++;
      continue;
    }

    await prisma.capability.create({
      data: capability,
    });
    created++;
  }

  console.log(`✅ Capabilities: ${created} criadas, ${skipped} já existiam`);
  console.log(`📊 Total de capabilities: ${capabilities.length}`);
}
